swagger: '2.0'
info:
  title: Bank Argent API documentation (Transaction part)
  description: Contains Transaction API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/{accountId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction visualization
      description: API for fetching account transactions on the current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: Numeric ID of the account to get
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Account transaction for the current month retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{accountId}/modify/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Modification transaction
      description: API for update account transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: Numeric ID of the account
          required: true
          type: integer
        - in: path
          name: transactionId
          description: Numeric ID of the transaction to modify
          required: true
          type: integer
        - in: body
          name: body
          description: field value to modify
          required: true
          schema:
            $ref: '#/definitions/TransactionModif'
      produces:
        - application/json
      responses:
        '200':
          description: Account transaction modification has been successful
          schema:
            $ref: '#/definitions/TransactionModifResponse'
        '400':
          description: Modification fail
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionModif:
    type: object
    properties:
      description:
        type: string
      category:
        type: string
      notes: 
        type: string
  TransactionsResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            transactions:
              type: object
              properties:
                id:
                  type: string
                releaseDate:
                  type: string
                  pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
                  example: "0000-00-00"
                description:
                  type: string
                amount:
                  type: integer
                balance:
                  type: integer
                transactionType:
                  type: string
                category:
                  type: string
                note:
                  type: string
  TransactionModifResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string